version: "3.7"

services:
  app:
      build: .
      ports:
        - "8090:8080"
  postgres:
      image: postgres:latest
      environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: 1234
        POSTGRES_DB: daxtas
      ports:
        - 5433:5432
#      volumes:
#        - postgres-s-data:/var/lib/postgresql/data
  #volumes:
      #postgres-s-data: